spring:
  application:
    name: fanpulse-event-api
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
  jackson:
    time-zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
