spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fanpulse}
    username: ${DB_USERNAME:fanpulse}
    password: ${DB_PASSWORD:fanpulse}
