CREATE TABLE events
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(200) NOT NULL,
    description TEXT         NOT NULL,
    category    VARCHAR(20)  NOT NULL,
    start_at    TIMESTAMPTZ  NOT NULL,
    end_at      TIMESTAMPTZ  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_events_category
        CHECK (category IN ('GAME', 'MOVIE', 'ANIME', 'MUSIC')),
    CONSTRAINT ck_events_time_range
        CHECK (start_at < end_at)
);

CREATE INDEX idx_events_start_at_id ON events (start_at, id);
CREATE INDEX idx_events_category ON events (category);
