CREATE TABLE candidates
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id      BIGINT       NOT NULL,
    name          VARCHAR(200) NOT NULL,
    display_order INTEGER      NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_candidates_event
        FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT uk_candidates_event_name
        UNIQUE (event_id, name),
    CONSTRAINT ck_candidates_display_order
        CHECK (display_order > 0)
);

CREATE INDEX idx_candidates_event_display_order
    ON candidates (event_id, display_order, id);

CREATE TABLE votes
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     BIGINT      NOT NULL,
    user_id      BIGINT      NOT NULL,
    candidate_id BIGINT      NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_votes_event
        FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT fk_votes_candidate
        FOREIGN KEY (candidate_id) REFERENCES candidates (id),
    CONSTRAINT uk_votes_event_user
        UNIQUE (event_id, user_id),
    CONSTRAINT ck_votes_user_id
        CHECK (user_id > 0),
    CONSTRAINT ck_votes_candidate_id
        CHECK (candidate_id > 0)
);

CREATE INDEX idx_votes_event_candidate
    ON votes (event_id, candidate_id);
